services:
  postgres:
    image: postgres:16-alpine
    container_name: docsob_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: docsob_user
      POSTGRES_PASSWORD: docsob_password
      POSTGRES_DB: docsob_db
    ports:
      - "5432:5432"
    volumes:
      - docsob_pgdata:/var/lib/postgresql/data

volumes:
  docsob_pgdata:
    driver: local
